server:
  port: 8080
  servlet:
    session:
      persistent: false
# DataSource Config
spring:
  thymeleaf:
    cache: false
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.139.129:3306/reimublog?allowMultiQueries=true&useSSL=false&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.126.129:3306/reimublog?allowMultiQueries=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 500
    #打印慢sql
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#mybatis
mybatis-plus:
  mapper-locations: classpath:/com/reimu/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.reimu.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    capital-mode: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
user:
  default:
    password: 123456